- name: copy properties file template
  template:
    src: "{{ playbook_dir }}/../fuzzer/test.properties"
    dest: "{{ ansible_env.HOME }}/"

- name: copy fuzzer jar
  copy:
    src: "{{ playbook_dir }}/../fuzzer/fuzzer.jar"
    dest: "{{ ansible_env.HOME }}/"

- name: Run fuzzer
  shell: "java -jar fuzzer.jar"
  args:
    chdir: "{{ ansible_env.HOME }}"

- name: Install test prioritization code dependancy
  shell: "npm install"
  args:
    chdir: "{{ tpa_home }}"
  become: yes

- pause:
    prompt: "start TPA?"

- name: Run test prioritization code
  shell: "node {{ tpa_home }}/main.js {{ jenkins_home }}/jobs/{{ job_name }}"
  register: tpa_res

- name: see TPA output
  debug:
    msg: "{{ tpa_res.stdout }}"
