---
- name: Install Java 8 PreReq
  apt: name=python-software-properties
  become: yes

- name: Add Java 8 Repo
  apt_repository: repo='ppa:webupd8team/java'
  become: yes

- name: Accept Oracle License
  debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true
  become: yes

- name: Install Java 8
  apt: name=oracle-java8-installer force=yes update_cache=yes cache_valid_time=3600
  become: yes

- name: Update apt package
  become: yes
  action: apt update_cache=yes
